"""032 — the ONE nginx stanza an app gets, and the applier that installs it.

Two substitutions only — a slug the registry already validated and a port the
supervisor allocated — into a fixed template. The applier writes atomically,
runs ``nginx -t`` and reloads only on success; a rejected stanza is removed
before anything reloads, so a bad app never takes the other vhosts down.
"""
import os
import re
import tempfile
from typing import Tuple

_SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
_DOMAIN_RE = re.compile(r"^[a-z0-9]+(?:[.-][a-z0-9]+)*$")

TEMPLATE = """# POLYROB app service (032) — generated by polyrob-apps.service; do not edit.
# app: {slug}  upstream: 127.0.0.1:{port}
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name {slug}.{base_domain};

    ssl_certificate     {cert_dir}/fullchain.pem;
    ssl_certificate_key {cert_dir}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # AGENT-built app. No ambient authority: this host never shares an origin with
    # the console, is never framed by third parties, and carries no referrer.
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
    client_max_body_size 1m;

    location / {{
        proxy_pass http://127.0.0.1:{port}/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 30s;
        proxy_connect_timeout 5s;
        proxy_next_upstream off;
    }}
}}
"""


def render_stanza(*, slug: str, host_port: int, base_domain: str, cert_dir: str) -> str:
    """The stanza text, or ``ValueError`` when an input is not the validated shape
    (defence in depth behind the registry's own validation)."""
    if not _SLUG_RE.fullmatch(str(slug)):
        raise ValueError(f"invalid slug {slug!r}")
    if not _DOMAIN_RE.fullmatch(str(base_domain)):
        raise ValueError(f"invalid base domain {base_domain!r}")
    port = int(host_port)
    if not (1 <= port <= 65535):
        raise ValueError(f"invalid port {host_port!r}")
    cert = str(cert_dir).rstrip("/")
    if not cert.startswith("/") or any(ch.isspace() or ch in ";{}" for ch in cert):
        raise ValueError(f"invalid cert dir {cert_dir!r}")
    return TEMPLATE.format(slug=slug, port=port, base_domain=base_domain, cert_dir=cert)


class NginxApplier:
    """Install/remove one ``<slug>.conf`` under *conf_dir* through *sys_runner*
    (``async (argv, *, input=None, timeout=None) -> (code, out, err)``)."""

    def __init__(self, conf_dir: str, sys_runner):
        self.conf_dir = conf_dir
        self._run = sys_runner

    def path_for(self, slug: str) -> str:
        if not _SLUG_RE.fullmatch(str(slug)):
            raise ValueError(f"invalid slug {slug!r}")
        return os.path.join(self.conf_dir, f"{slug}.conf")

    async def _test_and_reload(self) -> Tuple[bool, str]:
        code, _out, err = await self._run(["nginx", "-t"], timeout=30)
        if code != 0:
            return False, (err or "nginx -t failed").strip()[:400]
        code, _out, err = await self._run(["systemctl", "reload", "nginx"], timeout=60)
        if code != 0:
            return False, (err or "nginx reload failed").strip()[:400]
        return True, ""

    async def apply(self, slug: str, text: str) -> Tuple[bool, str]:
        path = self.path_for(slug)
        os.makedirs(self.conf_dir, exist_ok=True)
        previous = None
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as fh:
                previous = fh.read()
        fd, tmp = tempfile.mkstemp(prefix=f".{slug}.", suffix=".tmp", dir=self.conf_dir)
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, path)
        ok, err = await self._test_and_reload()
        if not ok:
            # Never leave a rejected stanza in the include dir: restore the previous
            # text (a live app keeps serving) or remove the new file.
            if previous is not None:
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(previous)
            else:
                try:
                    os.remove(path)
                except OSError:
                    pass
            return False, err
        return True, ""

    async def remove(self, slug: str) -> Tuple[bool, str]:
        path = self.path_for(slug)
        if not os.path.exists(path):
            return True, ""
        os.remove(path)
        return await self._test_and_reload()
