"""Static env-flag catalog extracted from docs/CONFIGURATION.md.

GENERATED — do not edit by hand. Regenerate with:
    python scripts/gen_flags_catalog.py
whenever the doc gains/renames flags (the contract test
tests/unit/core/test_flags.py asserts doc rows are a subset of this
catalog, so a doc-only addition fails CI until re-extracted; the same
test's parity check fails when this file drifts from the generator).
Each entry: (flag_name, group, documented_default). Entries whose name
contains "<" are dynamic patterns (e.g. POLYROB_<PROVIDER>_MODEL) and are
matched by pattern, not equality.
"""

CATALOG: list[tuple[str, str, str]] = [
    ("LLM_MAX_OUTPUT_TOKENS", "LLM / providers", "`16384`"),
    ("LLM_PROMPT_CACHE", "LLM / providers", "ON"),
    ("ANTHROPIC_PROMPT_CACHE", "LLM / providers", "ON"),
    ("GEMINI_PROMPT_CACHE", "LLM / providers", "OFF"),
    ("GEMINI_CACHE_TTL_MIN", "LLM / providers", "`10`"),
    ("OPENROUTER_PROMPT_CACHE", "LLM / providers", "OFF"),
    ("THINKING_CONFIG_ENABLED", "LLM / providers", "OFF"),
    ("THINK_SCRUBBER_ENABLED", "LLM / providers", "ON (`\"1\"`)"),
    ("STREAM_BRAIN_SCRUB", "LLM / providers", "ON (`\"true\"`)"),
    ("TASK_MAX_INPUT_TOKENS", "LLM / providers", "unset"),
    ("COMPACTION_MODEL", "LLM / providers", "unset"),
    ("COMPACTION_AUX_MODEL", "LLM / providers", "`''`"),
    ("COMPACTION_PROVIDER", "LLM / providers", "unset"),
    ("COMPACTION_AUTO_AUX", "LLM / providers", "OFF"),
    ("AUX_MODEL_JUDGE", "LLM / providers", "unset"),
    ("AUX_AUTO", "LLM / providers", "OFF"),
    ("AUX_PROVIDER", "LLM / providers", "unset"),
    ("AUX_MODEL_COMPACTION", "LLM / providers", "unset"),
    ("AUX_MODEL_REFLECTION", "LLM / providers", "unset"),
    ("AUX_PROVIDER_COMPACTION", "LLM / providers", "unset"),
    ("AUX_PROVIDER_JUDGE", "LLM / providers", "unset"),
    ("AUX_PROVIDER_REFLECTION", "LLM / providers", "unset"),
    ("AUX_FALLBACK_COMPACTION", "LLM / providers", "unset"),
    ("AUX_FALLBACK_JUDGE", "LLM / providers", "unset"),
    ("AUX_FALLBACK_REFLECTION", "LLM / providers", "unset"),
    ("REFLECTION_LLM_ENABLED", "LLM / providers", "**ON**"),
    ("NATIVE_TOOLS_DEBUG", "LLM / providers", "`''` (off)"),
    ("MEMORY_BACKEND", "Memory", "**`sqlite`** (**`local_vector` under `POLYROB_LOCAL`**)"),
    ("KB_ENABLED", "Memory", "OFF (**ON under POLYROB_LOCAL**)"),
    ("KB_AUTO_PREFETCH", "Memory", "OFF (**ON under POLYROB_LOCAL**)"),
    ("CONTEXT_REFERENCES_ENABLED", "Memory", "OFF (**ON under POLYROB_LOCAL**)"),
    ("MEMORY_REQUIRE_USER_ID", "Memory", "**ON** (`True`)"),
    ("MEMORY_VECTOR_MAX_DISTANCE", "Memory", "`0.6`"),
    ("MEMORY_TOOL_ENABLED", "Memory", "OFF"),
    ("MEMORY_TOOL_MAX_ENTRIES", "Memory", "`50`"),
    ("MEMORY_TOOL_MAX_CHARS", "Memory", "`2000`"),
    ("MEMORY_PREFETCH_CADENCE", "Memory", "`0` (**`3` under `POLYROB_LOCAL` and for autonomous sessions**)"),
    ("HMEM_SEMANTIC", "Memory", "`auto`"),
    ("HMEM_TAIL_PLACEMENT", "Memory", "ON"),
    ("MEMORY_THREAT_SCAN", "Memory", "OFF"),
    ("MEMORY_SEARCH_TOOL", "Memory", "**ON**"),
    ("MEMORY_STORE_ANSWER_ONLY", "Memory", "OFF (**ON under POLYROB_LOCAL**)"),
    ("MESSAGE_STORE_BACKEND", "Memory", "`''` (off)"),
    ("MAX_MEMORY_CACHE_SIZE", "Memory", "`30`"),
    ("MEMORY_CLEANUP_INTERVAL", "Memory", "`50`"),
    ("SKILL_PROGRESSIVE_DISCLOSURE", "Skills", "**ON**"),
    ("SKILL_CATALOG_INCLUDE_ALL", "Skills", "**ON everywhere**"),
    ("SKILLS_WRITABLE", "Skills", "OFF (**ON under POLYROB_LOCAL**)"),
    ("SKILLS_WRITABLE_REQUIRE_REVIEW", "Skills", "ON (`True`)"),
    ("SKILL_OVERWRITE_PROTECT", "Skills", "**ON**"),
    ("POLYROB_TRUST_PROJECT_SKILLS", "Skills", "**local-mode default: ON**; server: **forced OFF, no env override**"),
    ("AUTONOMY_POSTURE", "Autonomy & continuous-learning loops", "Default"),
    ("AGENT_COMPUTE_POSTURE", "Autonomy & continuous-learning loops", "Default"),
    ("SELF_WAKE_ENABLED", "Autonomy & continuous-learning loops", "OFF (**ON under POLYROB_LOCAL**)"),
    ("SELF_WAKE_MAX_REENTRIES", "Autonomy & continuous-learning loops", "`3`"),
    ("SELF_WAKE_IDLE_BACKOFF_SEC", "Autonomy & continuous-learning loops", "`30`"),
    ("BACKGROUND_REVIEW_ENABLED", "Autonomy & continuous-learning loops", "OFF (**ON under POLYROB_LOCAL**)"),
    ("BG_REVIEW_INTERVAL", "Autonomy & continuous-learning loops", "`10`"),
    ("BG_REVIEW_MAX_STEPS", "Autonomy & continuous-learning loops", "`8`"),
    ("CRON_RUN_LOOP", "Autonomy & continuous-learning loops", "**ON**"),
    ("CRON_DELIVERY_ENABLED", "Autonomy & continuous-learning loops", "OFF"),
    ("OWNER_DIGEST_ENABLED", "Autonomy & continuous-learning loops", "OFF"),
    ("CRON_DELIVERY_ALLOW_EXPLICIT_TARGET", "Autonomy & continuous-learning loops", "OFF"),
    ("TICKER_IDLE_BACKOFF_ENABLED", "Autonomy & continuous-learning loops", "OFF (**ON under POLYROB_LOCAL**)"),
    ("TICKER_IDLE_BACKOFF_MAX_MULTIPLIER", "Autonomy & continuous-learning loops", "`5`"),
    ("GOALS_ENABLED", "Autonomy & continuous-learning loops", "OFF (**ON under POLYROB_LOCAL**)"),
    ("GOAL_MAX_RETRIES", "Autonomy & continuous-learning loops", "`2`"),
    ("GOAL_CLAIM_TTL_SEC", "Autonomy & continuous-learning loops", "`900`"),
    ("GOAL_MAX_RUN_SECONDS", "Autonomy & continuous-learning loops", "`1800`"),
    ("GOAL_DISPATCH_INTERVAL_SEC", "Autonomy & continuous-learning loops", "`60`"),
    ("GOAL_MAX_CONCURRENT", "Autonomy & continuous-learning loops", "`2`"),
    ("GOAL_PLANNER_ENABLED", "Autonomy & continuous-learning loops", "OFF"),
    ("GOAL_PLANNER_MIN_READY", "Autonomy & continuous-learning loops", "`2`"),
    ("GOAL_PLANNER_COOLDOWN_SEC", "Autonomy & continuous-learning loops", "`3600`"),
    ("GOAL_PLANNER_HISTORY_N", "Autonomy & continuous-learning loops", "`10`"),
    ("GOAL_DAILY_QUOTA", "Autonomy & continuous-learning loops", "`6`"),
    ("GOAL_SELF_WAKE_ENABLED", "Autonomy & continuous-learning loops", "OFF"),
    ("GOAL_DEDUP_THRESHOLD", "Autonomy & continuous-learning loops", "`0.6`"),
    ("BUDGET_AWARE_AUTONOMY", "Autonomy & continuous-learning loops", "OFF (**ON under `AUTONOMY_POSTURE=owner-visible`/`full`**)"),
    ("AUTONOMY_BUDGET_USD", "Autonomy & continuous-learning loops", "`10`"),
    ("AUTONOMY_BUDGET_WINDOW_DAYS", "Autonomy & continuous-learning loops", "`1`"),
    ("CURATOR_ENABLED", "Autonomy & continuous-learning loops", "OFF (**ON under POLYROB_LOCAL**)"),
    ("CURATOR_INTERVAL_HOURS", "Autonomy & continuous-learning loops", "`168`"),
    ("CURATOR_STALE_DAYS", "Autonomy & continuous-learning loops", "`30`"),
    ("CURATOR_ARCHIVE_DAYS", "Autonomy & continuous-learning loops", "`90`"),
    ("INSIGHTS_TOOL", "Autonomy & continuous-learning loops", "OFF (**ON under POLYROB_LOCAL**)"),
    ("PROJECT_CONTEXT_AUTOLOAD", "Autonomy & continuous-learning loops", "OFF (**ON under POLYROB_LOCAL**)"),
    ("PROJECT_CONTEXT_MAX_TOKENS", "Autonomy & continuous-learning loops", "`20000`"),
    ("PROJECT_CONTEXT_SERVER_MODE", "Autonomy & continuous-learning loops", "OFF (NOT a safe-local flag)"),
    ("EPISODIC_MEMORY_ENABLED", "Autonomy & continuous-learning loops", "OFF (**ON under POLYROB_LOCAL or `AUTONOMY_POSTURE` owner-visible/full**)"),
    ("EPISODIC_DIGEST_INJECT", "Autonomy & continuous-learning loops", "OFF (**ON under POLYROB_LOCAL or `AUTONOMY_POSTURE` owner-visible/full**)"),
    ("CONTINUITY_BRIDGE_ENABLED", "Autonomy & continuous-learning loops", "OFF (**ON under POLYROB_LOCAL**)"),
    ("AUTONOMOUS_CONTINUITY_BRIDGE", "Autonomy & continuous-learning loops", "OFF"),
    ("SELF_EVOLUTION_TRANSPARENCY", "Autonomy & continuous-learning loops", "OFF (**ON under POLYROB_LOCAL**)"),
    ("GOAL_BLOCKER_ESCALATION", "Autonomy & continuous-learning loops", "OFF"),
    ("GOAL_EMPTY_PIPELINE_ESCALATE_AFTER", "Autonomy & continuous-learning loops", "`2`"),
    ("GOAL_COMPLETION_JUDGE", "Autonomy & continuous-learning loops", "OFF"),
    ("GOAL_JUDGE_TIMEOUT_SEC", "Autonomy & continuous-learning loops", "`60`"),
    ("REFLECTION_ON_SESSION_CLOSE", "Autonomy & continuous-learning loops", "OFF (**ON under `AUTONOMY_POSTURE` owner-visible/full**)"),
    ("AUTONOMY_STATE_DURABLE", "Autonomy & continuous-learning loops", "ON"),
    ("REFLECTION_SESSION_CLOSE_THRESHOLD", "Autonomy & continuous-learning loops", "`5`"),
    ("CONTINUITY_LLM_SUMMARY", "Autonomy & continuous-learning loops", "OFF (everywhere; NOT a safe-local flag)"),
    ("EPISODIC_RETENTION_DAYS", "Autonomy & continuous-learning loops", "`90`"),
    ("SUB_AGENTS_ENABLED", "Delegation / sub-agents", "**ON** (`'true'`; `BotConfig` field also `True`)"),
    ("SUBAGENT_LEAST_PRIVILEGE", "Delegation / sub-agents", "ON (`'true'`)"),
    ("DELEGATE_BLOCKED_TOOLS", "Delegation / sub-agents", "`{code_execution, coding, cronjob, x402_pay, hyperliquid, polymarket, git, github, process, tool_manage, mcp}`"),
    ("MAX_SUB_AGENT_DEPTH", "Delegation / sub-agents", "`1`"),
    ("MAX_CONCURRENT_SUB_AGENTS", "Delegation / sub-agents", "`3`"),
    ("MAX_ASYNC_SUB_AGENTS", "Delegation / sub-agents", "`2` (clamped ≤ concurrent)"),
    ("SUB_AGENT_TIMEOUT_SECONDS", "Delegation / sub-agents", "`600`"),
    ("SUB_AGENT_TIMEOUT", "Delegation / sub-agents", "`600`"),
    ("PARALLEL_SUBTASKS_TIMEOUT_SECONDS", "Delegation / sub-agents", "`900`"),
    ("PARALLEL_SUBTASKS_TIMEOUT", "Delegation / sub-agents", "`900`"),
    ("MCP_ENABLED", "Tools / code-exec / cron / approvals", "OFF (`False`)"),
    ("MAX_MCP_PER_STEP", "Tools / code-exec / cron / approvals", "`3`"),
    ("MCP_EXEC_RATE_PER_WINDOW", "Tools / code-exec / cron / approvals", "`20`"),
    ("MCP_EXEC_RATE_WINDOW_SEC", "Tools / code-exec / cron / approvals", "`60`"),
    ("MCP_ENCRYPTION_KEY", "Tools / code-exec / cron / approvals", "unset"),
    ("MCP_SELF_INSTALL_ENABLED", "Tools / code-exec / cron / approvals", "OFF (`False`)"),
    ("MCP_INSTALL_CATALOG_FILE", "Tools / code-exec / cron / approvals", "unset"),
    ("MCP_INSTALL_ALLOWLIST", "Tools / code-exec / cron / approvals", "unset"),
    ("ANYSITE_TOOL_ENABLED", "Tools / code-exec / cron / approvals", "ON (`True`)"),
    ("ANYSITE_API_KEY", "Tools / code-exec / cron / approvals", "unset"),
    ("CODING_TOOLS_ENABLED", "Tools / code-exec / cron / approvals", "OFF (**ON under POLYROB_LOCAL**)"),
    ("GIT_TOOLS_ENABLED", "Tools / code-exec / cron / approvals", "OFF (**ON under POLYROB_LOCAL**)"),
    ("GITHUB_TOOL_ENABLED", "Tools / code-exec / cron / approvals", "OFF (not safe-local)"),
    ("CODE_EXEC_ENABLED", "Tools / code-exec / cron / approvals", "OFF"),
    ("CODE_EXEC_BACKEND", "Tools / code-exec / cron / approvals", "`local_subprocess`"),
    ("CODE_EXEC_MAX_TIMEOUT_SEC", "Tools / code-exec / cron / approvals", "`30`"),
    ("CODE_EXEC_MAX_OUTPUT_BYTES", "Tools / code-exec / cron / approvals", "`100000`"),
    ("CODE_EXEC_DOCKER_IMAGE", "Tools / code-exec / cron / approvals", "`python:3.12-slim`"),
    ("CODE_EXEC_NETWORK", "Tools / code-exec / cron / approvals", "`none`"),
    ("CODE_EXEC_CONTAINER_MEMORY_MB", "Tools / code-exec / cron / approvals", "`1024`"),
    ("CODE_EXEC_CONTAINER_CPUS", "Tools / code-exec / cron / approvals", "`1.0`"),
    ("CODE_EXEC_PIDS_LIMIT", "Tools / code-exec / cron / approvals", "`256`"),
    ("CODE_EXEC_DOCKER_USER", "Tools / code-exec / cron / approvals", "unset → invoking uid:gid, or `65534:65534` (nobody:nogroup) when the host process itself runs as root"),
    ("CODE_EXEC_DOCKER_PERSISTENT", "Tools / code-exec / cron / approvals", "OFF (**ON at `AGENT_COMPUTE_POSTURE>=1`**)"),
    ("CODE_EXEC_PUBLISH_PORTS", "Tools / code-exec / cron / approvals", "`8000,5000,8080,3000`"),
    ("SHELL_TOOLS_ENABLED", "Tools / code-exec / cron / approvals", "OFF (**ON at `AGENT_COMPUTE_POSTURE>=1`**)"),
    ("SELF_ENV_ENABLED", "Tools / code-exec / cron / approvals", "OFF (**ON at `AGENT_COMPUTE_POSTURE>=2`**)"),
    ("POLYROB_INSTALL_TREE", "Tools / code-exec / cron / approvals", "repo root (2 levels up from `tools/self_env/tool.py`)"),
    ("POLYROB_SUPERVISED", "Tools / code-exec / cron / approvals", "OFF"),
    ("CRON_ENABLED", "Tools / code-exec / cron / approvals", "OFF"),
    ("WAKE_CHANGE_GATE", "Tools / code-exec / cron / approvals", "OFF (**ON under `AUTONOMY_POSTURE=full`**)"),
    ("MESSAGE_TOOL_ENABLED", "Tools / code-exec / cron / approvals", "OFF (**ON under POLYROB_LOCAL**)"),
    ("APPROVAL_REQUIRED_TOOLS", "Tools / code-exec / cron / approvals", "`''` (no-op)"),
    ("APPROVAL_PROVIDER", "Tools / code-exec / cron / approvals", "`auto`"),
    ("APPROVAL_TIMEOUT_SEC", "Tools / code-exec / cron / approvals", "`30`"),
    ("POLYROB_TOOL_DENYLIST", "Tools / code-exec / cron / approvals", "`''`"),
    ("POLYROB_AGENT_TOOLSET", "Tools / code-exec / cron / approvals", "unset"),
    ("TOOL_SCHEMA_ERROR_POLICY", "Tools / code-exec / cron / approvals", "`DROP_TOOL`"),
    ("TOOL_SCHEMA_SANITIZE", "Tools / code-exec / cron / approvals", "ON (`'true'`)"),
    ("UNTRUSTED_TOOL_RESULT_WRAP", "Tools / code-exec / cron / approvals", "**ON**"),
    ("ENABLE_GIF_CREATION", "Tools / code-exec / cron / approvals", "OFF"),
    ("FS_REALPATH_CONFINE", "Tools / code-exec / cron / approvals", "ON (`\"on\"`)"),
    ("BROWSER_ALLOW_PRIVATE_URLS", "Tools / code-exec / cron / approvals", "OFF (`'false'`)"),
    ("OPENAI_COMPAT_API_ENABLED", "API / server / sessions", "OFF"),
    ("SESSION_REGISTRY_BACKEND", "API / server / sessions", "`memory`"),
    ("API_HOST", "API / server / sessions", "`127.0.0.1`"),
    ("API_PORT", "API / server / sessions", "`9000`"),
    ("API_AUTH_TOKEN", "API / server / sessions", "unset"),
    ("API_RATE_LIMIT_RPM", "API / server / sessions", "`60`"),
    ("API_RATE_LIMIT_RPH", "API / server / sessions", "`1000`"),
    ("API_RATE_LIMIT_BURST", "API / server / sessions", "`10`"),
    ("CORS_ALLOW_ORIGINS", "API / server / sessions", "**Two independent consumers, two different defaults** — see note below"),
    ("WEBVIEW_DOMAIN", "API / server / sessions", "the reference deployment's public host (`webview/server.py`, `api/auth_endpoints.py`); `localhost:5050` (`agents/task/utils_webview.py`) — **inconsistent default across call sites; set `WEBVIEW_DOMAIN` for your own deployment**"),
    ("JWT_SECRET_KEY", "API / server / sessions", "unset (dev)"),
    ("A2A_BASE_URL", "API / server / sessions", "the reference deployment's base URL (set this to your own public URL)"),
    ("WEBVIEW_ACTIVITY_ENABLED", "API / server / sessions", "`true`"),
    ("WEBVIEW_ACTIVITY_TAIL_SEC", "API / server / sessions", "`2.0`"),
    ("WEBVIEW_READ_ONLY", "API / server / sessions", "`false`"),
    ("SESSION_TTL_SECONDS", "API / server / sessions", "`86400`"),
    ("MAX_SESSIONS_IN_MEMORY", "API / server / sessions", "`100`"),
    ("MAX_SESSIONS_PER_USER", "API / server / sessions", "`10`"),
    ("CREATED_SESSION_TTL_SECONDS", "API / server / sessions", "`3600`"),
    ("SESSION_RESET_MODE", "API / server / sessions", "`idle` (#7)"),
    ("SESSION_IDLE_MINUTES", "API / server / sessions", "`1440` (**720 POLYROB_LOCAL**)"),
    ("SESSION_RESET_HOUR", "API / server / sessions", "`4`"),
    ("SURFACE_GC_ENABLED", "API / server / sessions", "ON when local **+** chat bus on, else OFF"),
    ("UVICORN_HOST", "API / server / sessions", "`127.0.0.1`"),
    ("UVICORN_PORT", "API / server / sessions", "`9000`"),
    ("UVICORN_WORKERS", "API / server / sessions", "`1`"),
    ("UVICORN_RELOAD", "API / server / sessions", "OFF (`false`)"),
    ("ENVIRONMENT", "API / server / sessions", "`development` (varies by site)"),
    ("ENV", "API / server / sessions", "`development` (varies by site)"),
    ("LOG_LEVEL", "API / server / sessions", "`INFO`"),
    ("CHAT_TOOL_IDS", "API / server / sessions", "`task`"),
    ("CHAT_MAX_STEPS", "API / server / sessions", "`8`"),
    ("CHAT_SKIP_CREDIT_CHECK", "API / server / sessions", "ON (truthy)"),
    ("POLYROB_LOCAL", "Identity / polyrob / local profile", "OFF"),
    ("POLYROB_DATA_DIR", "Identity / polyrob / local profile", "unset"),
    ("POLYROB_PROJECT_DIR", "Identity / polyrob / local profile", "unset"),
    ("POLYROB_PROJECT_SECRET_REFUSE", "Identity / polyrob / local profile", "`0`"),
    ("POLYROB_REQUIRE_PAIRING", "Identity / polyrob / local profile", "OFF"),
    ("TELEGRAM_BOT_TOKEN", "Identity / polyrob / local profile", "unset"),
    ("ALLOWED_TELEGRAM_USER_IDS", "Identity / polyrob / local profile", "unset"),
    ("POLYROB_OWNER_TELEGRAM_ID", "Identity / polyrob / local profile", "unset"),
    ("POLYROB_OWNER_EMAIL", "Identity / polyrob / local profile", "unset"),
    ("BOT_OWNER_EMAIL", "Identity / polyrob / local profile", "unset"),
    ("SINGULAR_CHAT_ENABLED", "Identity / polyrob / local profile", "OFF (**ON for `polyrob telegram`**)"),
    ("TELEGRAM_SURFACE_ENABLED", "Identity / polyrob / local profile", "OFF (**ON for `polyrob telegram`**)"),
    ("TELEGRAM_INCREMENTAL_STREAM", "Identity / polyrob / local profile", "OFF"),
    ("TELEGRAM_STREAM_EDIT_INTERVAL_SEC", "Identity / polyrob / local profile", "`1.5`"),
    ("VOICE_TRANSCRIPTION_ENABLED", "Identity / polyrob / local profile", "OFF"),
    ("VOICE_TRANSCRIPT_ECHO", "Identity / polyrob / local profile", "ON"),
    ("VOICE_TRANSCRIPTION_MODEL", "Identity / polyrob / local profile", "`base`"),
    ("CORRESPONDENT_ACCESS_ENABLED", "Identity / polyrob / local profile", "OFF"),
    ("CORRESPONDENT_REQUIRE_APPROVAL", "Identity / polyrob / local profile", "ON (`True`)"),
    ("CORRESPONDENT_MAX_NEW_PER_DAY", "Identity / polyrob / local profile", "`20`"),
    ("EMAIL_SURFACE_ENABLED", "Identity / polyrob / local profile", "OFF (**ON for `polyrob email`**)"),
    ("EMAIL_IMAP_POLL_SEC", "Identity / polyrob / local profile", "`60`"),
    ("GMAIL_EMAIL", "Identity / polyrob / local profile", "unset"),
    ("GMAIL_APP_PASSWORD", "Identity / polyrob / local profile", "unset"),
    ("GMAIL_IMAP_SERVER", "Identity / polyrob / local profile", "`imap.gmail.com` / `smtp.gmail.com` / `587`"),
    ("GMAIL_SMTP_SERVER", "Identity / polyrob / local profile", "`imap.gmail.com` / `smtp.gmail.com` / `587`"),
    ("GMAIL_SMTP_PORT", "Identity / polyrob / local profile", "`imap.gmail.com` / `smtp.gmail.com` / `587`"),
    ("WHATSAPP_SURFACE_ENABLED", "Identity / polyrob / local profile", "OFF (**ON for `polyrob whatsapp`**)"),
    ("WHATSAPP_ACCESS_TOKEN", "Identity / polyrob / local profile", "unset"),
    ("WHATSAPP_PHONE_NUMBER_ID", "Identity / polyrob / local profile", "unset"),
    ("WHATSAPP_VERIFY_TOKEN", "Identity / polyrob / local profile", "unset"),
    ("WHATSAPP_WEBHOOK_SECRET", "Identity / polyrob / local profile", "unset"),
    ("WHATSAPP_TEMPLATE_NAME", "Identity / polyrob / local profile", "`task_ready`"),
    ("SELF_CONTEXT_WRITABLE", "Identity / polyrob / local profile", "OFF (**ON under POLYROB_LOCAL**)"),
    ("SELF_CONTEXT_REQUIRE_REVIEW", "Identity / polyrob / local profile", "ON (`True`)"),
    ("OWNER_DOC_WRITABLE", "Identity / polyrob / local profile", "OFF (**ON under POLYROB_LOCAL**)"),
    ("OWNER_DOC_REQUIRE_REVIEW", "Identity / polyrob / local profile", "ON (`True`)"),
    ("DATA_ROOT", "Identity / polyrob / local profile", "`./data/task`"),
    ("POLYROB_CLI_CONFIG", "Identity / polyrob / local profile", "unset"),
    ("POLYROB_GITIGNORE_DOTROB", "Identity / polyrob / local profile", "ON (`\"1\"`)"),
    ("CLI_WORKSPACE_LOCK", "Identity / polyrob / local profile", "ON (`\"1\"`)"),
    ("CLI_PREFER_ACTION_TEXT", "Identity / polyrob / local profile", "ON (`'true'`)"),
    ("POLYROB_INSTANCE_ID", "Identity / polyrob / local profile", "`\"rob\"` (`DEFAULT_INSTANCE_ID`)"),
    ("BOT_INSTANCE_ID", "Identity / polyrob / local profile", "`\"rob\"` (`DEFAULT_INSTANCE_ID`)"),
    ("POLYROB_OWNER_USER_ID", "Identity / polyrob / local profile", "unset → **instance id**"),
    ("BOT_OWNER_USER_ID", "Identity / polyrob / local profile", "unset → **instance id**"),
    ("POLYROB_LOCAL_OWNER", "Identity / polyrob / local profile", "unset"),
    ("SURFACE_SUPER_ADMIN_USER_IDS", "Identity / polyrob / local profile", "unset"),
    ("SURFACE_ADMIN_USER_IDS", "Identity / polyrob / local profile", "unset"),
    ("BILLING_FAILOVER_ENABLED", "Billing / x402 / wallet", "OFF"),
    ("X402_ENABLED", "Billing / x402 / wallet", "OFF (`'false'`)"),
    ("X402_CLIENT_ENABLED", "Billing / x402 / wallet", "OFF (`'false'`)"),
    ("X402_PAYMENT_RECIPIENT", "Billing / x402 / wallet", "`''`"),
    ("X402_INVOICE_ENABLED", "Billing / x402 / wallet", "OFF"),
    ("X402_INVOICE_MAX_USD", "Billing / x402 / wallet", "`50`"),
    ("X402_INVOICE_DAILY_MAX", "Billing / x402 / wallet", "`10`"),
    ("X402_SETTLEMENT_WATCH_INTERVAL_SEC", "Billing / x402 / wallet", "`60`"),
    ("X402_DEFAULT_CHAIN", "Billing / x402 / wallet", "`base`"),
    ("X402_FACILITATOR_URL", "Billing / x402 / wallet", "`''`"),
    ("X402_PRICE_USD", "Billing / x402 / wallet", "_derived_ (unset ⇒ economics-based, ~$30)"),
    ("X402_MAX_TOKENS_PER_REQUEST", "Billing / x402 / wallet", "`200000`"),
    ("X402_PRICE_MARKUP", "Billing / x402 / wallet", "`2.0`"),
    ("AGENT_WALLET_ENABLED", "Billing / x402 / wallet", "OFF"),
    ("AGENT_WALLET_NETWORK", "Billing / x402 / wallet", "`testnet`"),
    ("AGENT_WALLET_BACKEND", "Billing / x402 / wallet", "`local_eoa`"),
    ("AGENT_WALLET_MAX_PER_TX_USD", "Billing / x402 / wallet", "`1000000`"),
    ("AGENT_WALLET_OPERATIONAL_VENUE", "Billing / x402 / wallet", "`treasury`"),
    ("WALLET_DAILY_CAP_USD", "Billing / x402 / wallet", "unset (disabled)"),
    ("CREDIT_VALUE_USD", "Billing / x402 / wallet", "`0.01`"),
    ("WELCOME_BONUS", "Billing / x402 / wallet", "`100`"),
    ("EIP8004_ENABLED", "Billing / x402 / wallet", "OFF (`'false'`)"),
    ("ETH_PRICE_USD_OVERRIDE", "Billing / x402 / wallet", "unset"),
    ("ETH_PRICE_USD_MAX", "Billing / x402 / wallet", "`50000`"),
    ("DEPOSIT_MONITOR_ENABLED", "Billing / x402 / wallet", "OFF"),
    ("ENABLE_AUTH", "Billing / x402 / wallet", "OFF"),
    ("PAYMENT_MASTER_SEED", "Billing / x402 / wallet", "unset"),
    ("MASTER_SEED", "Billing / x402 / wallet", "unset"),
    ("POLYROB_POSTURE", "WebView / Console (deployment posture, owner login, branding)", "_derived_ (see below)"),
    ("WEBGATE_MULTITENANT", "WebView / Console (deployment posture, owner login, branding)", "OFF"),
    ("WEBGATE_HOST", "WebView / Console (deployment posture, owner login, branding)", "_posture-derived_ (`127.0.0.1` for `local`, `0.0.0.0` for `own_ops`/`multitenant`)"),
    ("WEBVIEW_HOST", "WebView / Console (deployment posture, owner login, branding)", "_posture-derived_ (`127.0.0.1` for `local`, `0.0.0.0` for `own_ops`/`multitenant`)"),
    ("WEBGATE_PORT", "WebView / Console (deployment posture, owner login, branding)", "`5050`"),
    ("WEBVIEW_PORT", "WebView / Console (deployment posture, owner login, branding)", "`5050`"),
    ("POLYROB_OWNER_USERNAME", "WebView / Console (deployment posture, owner login, branding)", "unset"),
    ("POLYROB_OWNER_PASSWORD_HASH", "WebView / Console (deployment posture, owner login, branding)", "unset"),
    ("POLYROB_CONSOLE_NAME", "WebView / Console (deployment posture, owner login, branding)", "`\"POLYROB Console\"`"),
    ("POLYROB_SUPPORT_URL", "WebView / Console (deployment posture, owner login, branding)", "`https://t.me/tmachinrobot`"),
    ("POLYROB_SUPPORT_HANDLE", "WebView / Console (deployment posture, owner login, branding)", "`@TMACHINROBOT`"),
    ("POLYROB_BRAND_URL", "WebView / Console (deployment posture, owner login, branding)", "`https://your-polyrob-host.example`"),
    ("POLYROB_ORG_URL", "WebView / Console (deployment posture, owner login, branding)", "`https://theselfrule.org`"),
    ("POLYROB_TERMS_URL", "WebView / Console (deployment posture, owner login, branding)", "`{POLYROB_BRAND_URL}/terms`"),
    ("POLYROB_PRIVACY_URL", "WebView / Console (deployment posture, owner login, branding)", "`{POLYROB_BRAND_URL}/privacy`"),
    ("TWITTER_ENABLED", "Misc / runtime knobs", "OFF (`'false'`)"),
    ("TWITTER_REQUIRE_APPROVAL", "Misc / runtime knobs", "ON (`'true'`)"),
    ("ALLOWED_REASONING_TURNS", "Misc / runtime knobs", "`1`"),
    ("COMPACTION_COOLDOWN_STEPS", "Misc / runtime knobs", "`3`"),
    ("COMPACTION_KEEP_RECENT", "Misc / runtime knobs", "`10`"),
    ("COMPACTION_TAIL_TOKEN_RATIO", "Misc / runtime knobs", "`0.20`"),
    ("COMPACTION_PER_MSG_CHARS", "Misc / runtime knobs", "`3000`"),
    ("COMPACTION_TOOL_RESULT_CHARS", "Misc / runtime knobs", "`2000`"),
    ("COMPACTION_MAX_SUMMARY_TOKENS", "Misc / runtime knobs", "`12000`"),
    ("COMPACTION_MIN_SUMMARY_TOKENS", "Misc / runtime knobs", "`2000`"),
    ("COMPACTION_MIN_SAVINGS_PCT", "Misc / runtime knobs", "`10.0`"),
    ("COMPACTION_CHECKPOINT", "Misc / runtime knobs", "ON (`'true'`)"),
    ("CONTEXT_OVERFLOW_THRESHOLD", "Misc / runtime knobs", "`0.90`"),
    ("MAX_REPETITIONS", "Misc / runtime knobs", "`2` (dev) / `3` (prod)"),
    ("UNCHANGED_STATE_THRESHOLD", "Misc / runtime knobs", "`3` (dev) / `4` (prod)"),
    ("EMPTY_ACTION_FAST_ESCALATE", "Misc / runtime knobs", "ON (`'true'`)"),
    ("MIN_STEPS_BEFORE_DONE", "Misc / runtime knobs", "`3`"),
    ("STEP_TIMEOUT_SECONDS", "Misc / runtime knobs", "`300`"),
    ("STALL_TIMEOUT_SECONDS", "Misc / runtime knobs", "`300`"),
    ("LLM_BASE_TIMEOUT_SECONDS", "Misc / runtime knobs", "`30`"),
    ("LLM_REQUEST_TIMEOUT_SECONDS", "Misc / runtime knobs", "`120`"),
    ("LLM_STREAM_TIMEOUT_SECONDS", "Misc / runtime knobs", "`300`"),
    ("MAX_CONSECUTIVE_FAILURES", "Misc / runtime knobs", "`5`"),
    ("MAX_PARSE_RETRIES", "Misc / runtime knobs", "`3`"),
    ("TASK_MODE", "Misc / runtime knobs", "`BALANCED`"),
    ("TASK_PERSONALITY_BLOCK", "Misc / runtime knobs", "OFF (`'false'`)"),
    ("ANONYMIZED_TELEMETRY", "Misc / runtime knobs", "ON (`True`)"),
    ("DESTRUCTIVE_ACTION_POLICY", "Misc / runtime knobs", "`none`"),
    ("HITL_MODE", "Misc / runtime knobs", "`chat`"),
    ("VALIDATE_OUTPUT", "Misc / runtime knobs", "OFF"),
    ("INTERRUPT_REDIRECT", "Misc / runtime knobs", "OFF"),
    ("POLYROB_ENV", "Misc / runtime knobs", "`development` (falls back to `ENVIRONMENT`)"),
    ("POLYROB_ENV_KEY_BACKFILL", "Misc / runtime knobs", "ON (`\"1\"`)"),
    ("POLYROB_HOME", "Misc / runtime knobs", "`~/.polyrob`"),
    ("POLYROB_IN_DOCKER", "Misc / runtime knobs", "unset"),
    ("POLYROB_NONINTERACTIVE", "Misc / runtime knobs", "unset"),
    ("POLYROB_PERSISTENT_INPUT", "Misc / runtime knobs", "ON"),
    ("POLYROB_PERSONA", "Misc / runtime knobs", "unset"),
    ("POLYROB_PLAIN", "Misc / runtime knobs", "OFF"),
    ("POLYROB_WORKSPACE_LOCK_DIR", "Misc / runtime knobs", "set by bootstrap"),
    ("WEB_FETCH_ALLOW_PRIVATE_URLS", "Web fetch (Tier-1 lightweight web reader)", "OFF"),
    ("CRYPTO_TRADE_LIVE_ENABLED", "Crypto trading (Polymarket / Hyperliquid)", "OFF"),
    ("POLYMARKET_TRADING_ENABLED", "Crypto trading (Polymarket / Hyperliquid)", "OFF"),
    ("HYPERLIQUID_TRADING_ENABLED", "Crypto trading (Polymarket / Hyperliquid)", "OFF"),
    ("POLYMARKET_TRADE_MAX_USD", "Crypto trading (Polymarket / Hyperliquid)", "`5`"),
    ("HYPERLIQUID_TRADE_MAX_USD", "Crypto trading (Polymarket / Hyperliquid)", "`5`"),
    ("POLYROB_UPDATE_REPO", "`polyrob update` — self-update & rollback", "derived from the dist Project-URL, else `theselfruleorg/polyrob`"),
    ("POLYROB_UPDATE_PYPI", "`polyrob update` — self-update & rollback", "`polyrob`"),
    ("PFP_PUSH_TWITTER", "Avatar (pfp)", "OFF"),
    ("PFP_PUSH_TELEGRAM", "Avatar (pfp)", "OFF"),
]
