"""Contract test for the polyrob-user-guide config reference (owner-UX P3 T1).

Mirrors tests/unit/core/test_flags.py's pattern: the committed reference must
be exactly what the checked-in generator produces (drift guard), and every
flag documented in the runtime catalog (core/flags_catalog.py::CATALOG) must
be discoverable in the compact reference the skill reads.
"""
import subprocess
import sys
from pathlib import Path

import pytest

from core.flags_catalog import CATALOG

REPO_ROOT = Path(__file__).resolve().parents[3]
GENERATOR = REPO_ROOT / "scripts" / "gen_user_guide_refs.py"
REFERENCE = (
    REPO_ROOT / "data" / "prompts" / "skills" / "polyrob-user-guide"
    / "references" / "configuration.md"
)


def test_reference_is_up_to_date_with_generator():
    """The committed reference must be exactly what the checked-in generator
    produces (the standard generated-file contract, same as
    test_flags.py::test_generator_parity_with_checked_in_catalog`).

    ``scripts/`` is private-only (never shipped to the public repo — the whole
    directory is on the publish denylist), so skip this check when the
    generator is absent; the reference file itself still ships and the
    catalog-coverage test below still runs everywhere.
    """
    if not GENERATOR.exists():
        pytest.skip("gen_user_guide_refs generator is private-only (scripts/ not shipped)")
    proc = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        capture_output=True, text=True,
    )
    assert proc.returncode == 0, proc.stderr


def test_reference_file_exists_and_has_content():
    assert REFERENCE.exists(), f"missing generated reference: {REFERENCE}"
    text = REFERENCE.read_text()
    assert text.startswith("<!-- GENERATED by scripts/gen_user_guide_refs.py")
    assert "## LLM / providers" in text


def test_every_catalog_flag_appears_in_reference():
    """Every flag name known to the runtime catalog must be findable in the
    compact reference (subset assertion, mirroring test_flags.py's doc-rows
    ⊆ registry pattern) — a name absent here means the skill's reference lost
    a flag the runtime still resolves.

    Dynamic-pattern names (containing ``<...>``, e.g. ``POLYROB_<PROVIDER>_MODEL``)
    are skipped: they're not resolved by literal-name lookup, so their absence
    (or presence with the placeholder unexpanded) would be a false negative —
    same tolerance test_flags.py's ``_NAME_RE`` applies by construction.
    """
    text = REFERENCE.read_text()
    missing = []
    for name, _group, _default in CATALOG:
        if "<" in name:
            continue
        if name not in text:
            missing.append(name)
    assert not missing, (
        f"{len(missing)} flag(s) in core/flags_catalog.py::CATALOG missing from "
        f"the user-guide reference — run `python scripts/gen_user_guide_refs.py`: "
        f"{missing[:10]}"
    )
